Display figures on a new github pages site.
OSIPI/TF2.4_IVIM-MRI_CodeCollection pull request #49
Opened 2024-03-02 02:07 UTC by AhmedBasem20

### Describe the changes you have made in this PR

Displayed the generated plots from the analysis workflow to a new github-pages site.
### Results
Example from my fork: https://ahmedbasem20.github.io/TF2.4_IVIM-MRI_CodeCollection/

@etpeterson To enable this on this repository we need the following steps:

1. create a new branch named `gh-pages`.
2. From the pages section on the repository settings, set `gh-pages` as a source branch.
<img width="1228" alt="image" src="https://github.com/OSIPI/TF2.4_IVIM-MRI_CodeCollection/assets/62952819/30dfc04c-35e8-40da-8b95-8e241e0c627e">

### Link this PR to an issue [optional]

Fixes #46

2024-03-02 06:23 UTC, etpeterson commented on .github/workflows/analysis.yml
> +      - name: Download artifacts
Is this download step necessary? The figures should already be present

2024-03-02 06:27 UTC, etpeterson commented on index.html
> +<!DOCTYPE html>
Perhaps move this into a website folder?

2024-03-02 06:27 UTC, etpeterson commented on index.html
> +    <embed src="durations.pdf" type="application/pdf" frameborder="0" scrolling="auto">
Probably move curve and duration to the bottom as they're probably less interesting.

2024-03-03 23:11 UTC, etpeterson commented
This all looks good but I'm wondering how this actually works on the repository. We just went through a big cleaning process and we don't want to have to deal with that again, so I'm hyper vigilant about uploading things to the repository. It _seems_ like this pushes the pdfs to the repository each time. I see [this](https://www.reddit.com/r/rust/comments/wy3j50/psa_if_youre_using_ghpages_to_host_your/) discussion about that, for example. That then points to [this](https://github.com/actions/deploy-pages) as a way to push but not keep the history.

In short, I think whatever we do, we don't want the history of the pdfs pushed, just the most recent.

2024-03-03 23:11 UTC, etpeterson requested changes

2024-03-03 23:11 UTC, etpeterson commented on .github/workflows/analysis.yml
> +        uses: JamesIves/github-pages-deploy-action@4.1.1
How does this differ from [this](https://github.com/actions/upload-pages-artifact)? Using the official one seems to be the safer bet, if possible.

2024-03-04 11:45 UTC, AhmedBasem20 commented
Thanks @etpeterson for the review, I used the deployment method you suggested and it worked fine, see: https://github.com/AhmedBasem20/TF2.4_IVIM-MRI_CodeCollection/actions/runs/8139256741

2024-03-05 05:54 UTC, etpeterson commented
> Thanks @etpeterson for the review, I used the deployment method you suggested and it worked fine, see: https://github.com/AhmedBasem20/TF2.4_IVIM-MRI_CodeCollection/actions/runs/8139256741

This run only ran 4 algorithms but I see on the hosted site that all of them ran. Why this discrepancy? I don't see anything in the code that should be changing that.

2024-03-05 10:08 UTC, AhmedBasem20 commented
My bad. I wanted to see the results quickly, so I removed most of the algorithms on this workflow. But the workflow of the committed code on this pull request works fine: https://github.com/AhmedBasem20/TF2.4_IVIM-MRI_CodeCollection/actions/runs/8139531990 

> I also see there is a few pushes that caused commits, but I don't see any changes more recently. I'm not sure how this should act, but with the algorithm discrepancy I'm still hesitant to merge until it's all clear.


Those pushes caused by the old action that deploys to `gh-pages`. It is removed now.

2024-03-06 05:53 UTC, etpeterson requested changes
This looks good, just one small comment. It is a little opaque to me how the publishing works though. Have you found a good resource?

Perhaps another change would be however we should structure the website. I'm imagining a base page and we link to the results from there, or perhaps they're on the base page somewhere. Right now it's just the results page, correct? Maybe the comment in the related issue will get answered to help here.

2024-03-06 05:53 UTC, etpeterson commented on .github/workflows/analysis.yml
>        - 'main'
This workflow runs on `main` and anything that starts with `analysis`. We probably only want the website to update from the `main` branch, so can we run it but not upload if it's running an `analysis` branch?

2024-03-06 13:59 UTC, AhmedBasem20 commented
@etpeterson the publishing action depends on the artifact we uploaded, I used [this action](https://github.com/actions/starter-workflows/blob/main/pages/static.yml) as a reference.
Will the documentation page be on this website? If so, we build this page along with the docs and add it there. But for now, I can improve the layout of the current HTML page until we get the documentation.

2024-03-07 05:09 UTC, etpeterson commented
This looks good. I think there's an open question about where the results should land and if the index.html page should start with a little more on there, but that's for @petravanhoudt and @oliverchampion.

2024-03-22 15:38 UTC, etpeterson commented
Just following up @oliverchampion or @petravanhoudt if you have ideas on the structure of the page.

2024-03-25 09:18 UTC, AhmedBasem20 commented
superseded by #59

2024-03-25 09:18 UTC, closed without merging