Unit testing tolerances + more consistent definition of SNR
OSIPI/TF2.4_IVIM-MRI_CodeCollection pull request #79
Opened 2024-08-21 15:50 UTC by oliverchampion

### Describe the changes you have made in this PR

1: I want to have a more consistent definition of SNR in the phantom. By putting T1T2 to False, T1 and T2 effects are ignored and all signal starts at 1. This means that SNR = 1/noise.
2: I have tried to make tolerances scale with SNR and f.  --> This is also meant to get the discussion going for Friday and can be adapted accordingly

### Link this PR to an issue [optional]

1 Fixes _#76
2 Fixes _#75

### Checklist

- [ X ] Self-review of changed code
- [ X ] Added automated tests where applicable
- [ ] Update Docs & Guides

2024-08-29 01:04 UTC, etpeterson requested changes
Also a merge conflict?

2024-08-29 01:04 UTC, etpeterson commented on tests/IVIMmodels/unit_tests/test_ivim_fit.py
> +        if dyn_rtol["scale_f"]:
I think this is a misnomer and should be renamed. I thought something called `scale_f` would be scaling the `f` parameter. Instead it scales the others by `f`.

2024-08-29 01:04 UTC, etpeterson commented on tests/IVIMmodels/unit_tests/test_ivim_fit.py
> +            tolerances["rtol"] = {"f": scale * dyn_rtol["f"], "D": scale * dyn_rtol["D"]/0.9,"Dp": scale * dyn_rtol["Dp"]/0.1}
Why 0.9 and 0.1? Also why would we not want to scale by `f`?

2024-08-29 01:04 UTC, etpeterson commented on tests/IVIMmodels/unit_tests/test_ivim_fit.py
> +    signal = np.abs(signal) #Oliver: do we need this for unit testing? It will bias the fits by forcing positive signals.
Probably not necessary.

2024-08-29 01:04 UTC, etpeterson commented on tests/IVIMmodels/unit_tests/test_ivim_fit.py
> +    signal /= signal[0] # this scales noise differenly. I have now made sure signal is produced with amplitude 1 if right flags are selected. Then  SNR is fixed. Then, this sentence may be redundant
Should probably be removed, at least eventually each algorithm should have their own scaling built in. For now maybe it needs to stay though?

2025-01-03 15:05 UTC, oliverchampion commented on tests/IVIMmodels/unit_tests/test_ivim_fit.py
> +        if dyn_rtol["scale_f"]:
Done in next upload

2025-01-03 15:06 UTC, oliverchampion commented on tests/IVIMmodels/unit_tests/test_ivim_fit.py
> +        if dyn_atol["scale_f"]:
Done in next upload

2025-01-03 15:11 UTC, oliverchampion commented on tests/IVIMmodels/unit_tests/test_ivim_fit.py
> +        if dyn_rtol["scale_f"]:
Changed to scale_by_f

2025-01-03 15:15 UTC, oliverchampion commented on tests/IVIMmodels/unit_tests/test_ivim_fit.py
> +            tolerances["rtol"] = {"f": scale * dyn_rtol["f"], "D": scale * dyn_rtol["D"]/0.9,"Dp": scale * dyn_rtol["Dp"]/0.1}
we will scale by f is "scale_by_f" is true. Otherwise, we will scale with predefined ratio, which assumes 10% perfusion. 
If we always want to scale by f, that is also okay :).

2025-01-03 15:16 UTC, oliverchampion commented on tests/IVIMmodels/unit_tests/test_ivim_fit.py
> +    signal /= signal[0] # this scales noise differenly. I have now made sure signal is produced with amplitude 1 if right flags are selected. Then  SNR is fixed. Then, this sentence may be redundant
Needs to go to wrapper. For now I also rescale here. Can be removed once fixed in wrapper.

2025-01-03 15:23 UTC, oliverchampion commented on tests/IVIMmodels/unit_tests/test_ivim_fit.py
> +            tolerances["rtol"] = {"f": scale * dyn_rtol["f"], "D": scale * dyn_rtol["D"]/0.9,"Dp": scale * dyn_rtol["Dp"]/0.1}
Good point. I now automatically scale by f, instead. This solves this comment and the three above

2025-01-03 15:25 UTC, oliverchampion commented
I think now it simplifies testing. Not sure whether "dynamic testing" has a place in our testing line, although it cannot harm to keep it in there:).
test boundaries are hard-coded now in "tolerance_helper()"

2025-01-03 16:29 UTC, oliverchampion commented on tests/IVIMmodels/unit_tests/test_ivim_fit.py
> +    signal = np.abs(signal) #Oliver: do we need this for unit testing? It will bias the fits by forcing positive signals.
This had to be moved to some individual fit algorithms to prevent them from failing

2025-02-28 14:35 UTC, etpeterson requested changes

2025-02-28 14:35 UTC, etpeterson commented on src/original/OGC_AmsterdamUMC/LSQ_fitting.py
> +        Dt, Fp = 0+params[0], 1 - params[1]
`0+params[0]`, why the `0+` part? I see it in a few other places too.

2025-02-28 14:35 UTC, etpeterson commented on src/original/OGC_AmsterdamUMC/LSQ_fitting.py
Is this algorithm wrapped? I just want to make sure these changes are also made there, if necessary.

2025-03-07 12:29 UTC, oliverchampion commented on src/original/OGC_AmsterdamUMC/LSQ_fitting.py
Not sure what you mean here? no code was selected.

2025-03-07 12:43 UTC, oliverchampion commented on src/original/OGC_AmsterdamUMC/LSQ_fitting.py
> +        Dt, Fp = 0+params[0], 1 - params[1]
I forgot, but I think it gave some errors in some cases when I did not do this. Although I cannot imagine what type of error and I also cannot reproduce these errors; but I am a bit doubtful in removing it in case it bites me further down the line.

2025-03-07 12:49 UTC, oliverchampion commented on src/original/OGC_AmsterdamUMC/LSQ_fitting.py
> +        Dt, Fp = 0+params[0], 1 - params[1]
Changed my mind and changed it

2025-03-17 04:39 UTC, etpeterson commented
Looks like some change in here broke python 3.11, our most recent version of python we're testing with.

2025-03-17 04:42 UTC, etpeterson requested changes
Main issue is the test failure on Py3.11.

2025-03-17 04:42 UTC, etpeterson commented on src/original/OGC_AmsterdamUMC/LSQ_fitting.py
This is the origina/OGC_AmsterdamUMC/LSQ_fitting.py code. You made changes but it's not a wrapped algorithm. Just wanted to make sure it's all as intended.

2025-03-17 08:21 UTC, oliverchampion commented on src/original/OGC_AmsterdamUMC/LSQ_fitting.py
I think this went well, as the algorithm's wrap is passing the testing :).

2025-03-17 08:24 UTC, oliverchampion commented
Ah, it seems some import was occuring that no longer exists/was needed in 3.11. Either way, the import was never used, so I removed it. Should run now.

2025-03-17 14:25 UTC, merged